# Generated by Django 4.1 on 2022-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
