# Generated by Django 4.1 on 2022-08-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_todo_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
