# Generated by Django 4.1 on 2022-08-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_remove_todo_endtime_remove_todo_starttime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
    ]
